### ISSUE TITLE
Error mqtt

### ISSUE THREAD

**Issue by maik-dmxc** [croedel/M-TEC-API#3]
Hi i get an message when starting MTEC_mqtt.py

```
pi@raspberrypi:~/M-TEC-API $ sudo python3 MTEC_mqtt.py
Traceback (most recent call last):
  File "MTEC_mqtt.py", line 148, in <module>
    main()
  File "MTEC_mqtt.py", line 118, in main
    if cfg['DEBUG'] == True:
KeyError: 'DEBUG'

```
what i'm doing wrong?

do have to set mqtt Username & password?

regards Maik

**Comment by croedel** [comment]
Ah sorry - I forgot to add some new config entries to templates/config.yaml
Following entries were missing:
POLL_FREQUENCY : 60         # query data every N seconds
DEBUG : False                # Set to True to get verbose debug messages
WRITE_STATION_DATA : True   # Choose if you want to write station data to MQTT
WRITE_DEVICE_DATA : True    # Choose if you want to write device data to MQTT

**Comment by croedel** [comment]
MQTT Username and password are optional. They are only required, if your broker is set up to require auth
