### ISSUE TITLE
MQTT stops working after some time

### ISSUE THREAD

**Issue by Merceile** [croedel/M-TEC-API#5]
Hi,

the script works but it stops after some time.

[ERROR] MTECapi.py: Error while retrieving device list for stationId 'xxxxx': {'code': '3010107', 'msg': 'System busy, please try again later', 'data': None, 'time': '2023-10-30T06:33:53.665+00:00'}
Traceback (most recent call last):
  File "/home/mtec/MTEC_mqtt.py", line 191, in <module>
    main()
  File "/home/mtec/MTEC_mqtt.py", line 172, in main
    pvdata = read_MTEC_station_data(api, station_id)
  File "/home/mtec/MTEC_mqtt.py", line 89, in read_MTEC_station_data
    pvdata["day_production"] = normalize(data["todayEnergy"])              # Energy produced by the PV today
TypeError: 'NoneType' object is not subscriptable

The Poll Frequency is set to 1 second. This might be the issue.

Any Ideas?

Thank you in advance.

**Comment by croedel** [comment]
Hi, I assume this behaviour comes from an abuse blocking, which M-TEC applied for their backend / API.
The data  is anyhow collected only once per minute.  I would not recommmend to poll more often than 1 min, better 5 min.
